[patch] Discover(...) now static as we have it static in net.cpp
To avoid this error:

net.cpp: In function ‘void Discover(boost::thread_group&)’:
net.cpp:1910:54: error: ‘void Discover(boost::thread_group&)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 void static Discover(boost::thread_group& threadGroup)
                                                      ^
In file included from net.cpp:10:0:
net.h:175:6: note: previous declaration of ‘void Discover(boost::thread_group&)’
 void Discover(boost::thread_group& threadGroup);
      ^

So we should add static in .h or remove static from.cpp ...