build: mac bump macOS SDK to 10.15.6 (12.1)
Qt: linux and windows builds of Qt compile with -c++std c++11, darwin
require -c++std c++1z, bcz of multiple:

Compiling .moc/moc_qplatformprintplugin.cpp
qappletestlogger.cpp:107:20: error: no matching constructor for initialization of 'MessageData'
            return MessageData{QtInfoMsg, "pass"};
                   ^          ~~~~~~~~~~~~~~~~~~~
qappletestlogger.cpp:86:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
struct MessageData
       ^

If trying to compile with c++11.