komodo_hardfork: avoid build error with CXXFLAGS='-g -O0'
Issue: if we will try to build KomodoOcean with CXXFLAGS='-g -O0'
we will get the following error during linkage:

usr/bin/ld: libbitcoin_util.a(libbitcoin_util_a-util.o): in function `__static_initialization_and_destruction_0(int, int)':
/home/decker/KomodoOcean/src/komodo_hardfork.h:19: undefined reference to `nStakedDecemberHardforkTimestamp'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:19: undefined reference to `nS4Timestamp'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:19: undefined reference to `nS5Timestamp'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:19: undefined reference to `nS6Timestamp'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:20: undefined reference to `nDecemberHardforkHeight'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:20: undefined reference to `nS4HardforkHeight'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:20: undefined reference to `nS5HardforkHeight'
/usr/bin/ld: /home/decker/KomodoOcean/src/komodo_hardfork.h:20: undefined reference to `nS6HardforkHeight'

So, we need to include komodo_hardfork.cpp into libbitcoin_util_a_SOURCES
or delete include of komodo_hardfork.h from komodo_globals.h.