[patch] komodo_stateupdate: disable fread
we have turned off komodo_parsestatefile. it was temporary disabled
by Ocean. but still have read from file. as a result, when building
on Linux we have following error:

komodo.h: In function ‘void komodo_stateupdate(int32_t, uint8_t (*)[33], uint8_t, uint8_t, uint256, uint64_t, uint8_t, uint32_t*, uint8_t, int32_t, uint32_t, uint64_t, uint8_t*, uint16_t, uint16_t)’:
komodo.h:425:41: error: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Werror=unused-result]
                     fread(mp,1,fsize,fp);

This fix helps to avoid it. We don't need read anything from this file,
because it parsing is turned off.