add -ldl for linking librustzcash
to avoid this error:

/usr/bin/ld: KomodoOcean/depends/x86_64-unknown-linux-gnu/lib/librustzcash.a(rustzcash-528a6cf1ab5e575d.rustzcash0.rcgu.o): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

configure: Don't add -ldl to RUST_LIBS for mingw32